const movies = [
  {
    adult: false,
    backdrop_path: "/7ZO9yoEU2fAHKhmJWfAc2QIPWJg.jpg",
    genre_ids: [28, 878, 27],
    id: 766507,
    original_language: "en",
    original_title: "Prey",
    overview:
      "When danger threatens her camp, the fierce and highly skilled Comanche warrior Naru sets out to protect her people. But the prey she stalks turns out to be a highly evolved alien predator with a technically advanced arsenal.",
    popularity: 9839.591,
    poster_path: "/ujr5pztc1oitbe7ViMUOilFaJ7s.jpg",
    release_date: "2022-08-02",
    title: "Prey",
    video: false,
    vote_average: 8.1,
    vote_count: 2894,
  },
  {
    adult: false,
    backdrop_path: "/ugS5FVfCI3RV0ZwZtBV3HAV75OX.jpg",
    genre_ids: [16, 878, 28],
    id: 610150,
    original_language: "ja",
    original_title: "ドラゴンボール超：スーパーヒーロー",
    overview:
      "The Red Ribbon Army, an evil organization that was once destroyed by Goku in the past, has been reformed by a group of people who have created new and mightier Androids, Gamma 1 and Gamma 2, and seek vengeance against Goku and his family.",
    popularity: 8660.942,
    poster_path: "/rugyJdeoJm7cSJL1q4jBpTNbxyU.jpg",
    release_date: "2022-06-11",
    title: "Dragon Ball Super: Super Hero",
    video: false,
    vote_average: 7.5,
    vote_count: 119,
  },
  {
    adult: false,
    backdrop_path: "/p1F51Lvj3sMopG948F5HsBbl43C.jpg",
    genre_ids: [28, 12, 14],
    id: 616037,
    original_language: "en",
    original_title: "Thor: Love and Thunder",
    overview:
      "After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now inexplicably wields Mjolnir as the Relatively Mighty Girl Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.",
    popularity: 7686.423,
    poster_path: "/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
    release_date: "2022-07-06",
    title: "Thor: Love and Thunder",
    video: false,
    vote_average: 6.8,
    vote_count: 1970,
  },
  {
    adult: false,
    backdrop_path: "/jauI01vUIkPA0xVsamGj0Gs1nNL.jpg",
    genre_ids: [12, 28, 878],
    id: 507086,
    original_language: "en",
    original_title: "Jurassic World Dominion",
    overview:
      "Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history’s most fearsome creatures.",
    popularity: 4973.973,
    poster_path: "/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg",
    release_date: "2022-06-01",
    title: "Jurassic World Dominion",
    video: false,
    vote_average: 7.1,
    vote_count: 2931,
  },
  {
    adult: false,
    backdrop_path: "/nmGWzTLMXy9x7mKd8NKPLmHtWGa.jpg",
    genre_ids: [16, 12, 35, 14],
    id: 438148,
    original_language: "en",
    original_title: "Minions: The Rise of Gru",
    overview:
      "A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.",
    popularity: 4558.565,
    poster_path: "/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg",
    release_date: "2022-06-29",
    title: "Minions: The Rise of Gru",
    video: false,
    vote_average: 7.8,
    vote_count: 1520,
  },
  {
    adult: false,
    backdrop_path: "/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg",
    genre_ids: [28, 18],
    id: 361743,
    original_language: "en",
    original_title: "Top Gun: Maverick",
    overview:
      "After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.",
    popularity: 4418.797,
    poster_path: "/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    release_date: "2022-05-24",
    title: "Top Gun: Maverick",
    video: false,
    vote_average: 8.3,
    vote_count: 2357,
  },
  {
    adult: false,
    backdrop_path: "/5L6RPHHUFlsliTqKRmUxFnIkXpR.jpg",
    genre_ids: [28, 14, 27],
    id: 755566,
    original_language: "en",
    original_title: "Day Shift",
    overview:
      "An LA vampire hunter has a week to come up with the cash to pay for his kid's tuition and braces. Trying to make a living these days just might kill him.",
    popularity: 3674.607,
    poster_path: "/bI7lGR5HuYlENlp11brKUAaPHuO.jpg",
    release_date: "2022-08-10",
    title: "Day Shift",
    video: false,
    vote_average: 6.7,
    vote_count: 482,
  },
  {
    adult: false,
    backdrop_path: "/AfvIjhDu9p64jKcmohS4hsPG95Q.jpg",
    genre_ids: [27, 53],
    id: 756999,
    original_language: "en",
    original_title: "The Black Phone",
    overview:
      "Finney Blake, a shy but clever 13-year-old boy, is abducted by a sadistic killer and trapped in a soundproof basement where screaming is of little use. When a disconnected phone on the wall begins to ring, Finney discovers that he can hear the voices of the killer’s previous victims. And they are dead set on making sure that what happened to them doesn’t happen to Finney.",
    popularity: 3467.054,
    poster_path: "/lr11mCT85T1JanlgjMuhs9nMht4.jpg",
    release_date: "2022-06-22",
    title: "The Black Phone",
    video: false,
    vote_average: 7.9,
    vote_count: 2019,
  },
  {
    adult: false,
    backdrop_path: "/3VQj6m0I6gkuRaljmhNZl0XR3by.jpg",
    genre_ids: [16, 12, 35, 14],
    id: 585511,
    original_language: "en",
    original_title: "Luck",
    overview:
      "Suddenly finding herself in the never-before-seen Land of Luck, the unluckiest person in the world must unite with the magical creatures there to turn her luck around.",
    popularity: 2799.933,
    poster_path: "/1HOYvwGFioUFL58UVvDRG6beEDm.jpg",
    release_date: "2022-08-05",
    title: "Luck",
    video: false,
    vote_average: 8.2,
    vote_count: 481,
  },
  {
    adult: false,
    backdrop_path: "/2oXQpm0wfOkIL0jBJABbL5AfMs6.jpg",
    genre_ids: [27, 9648, 53],
    id: 760104,
    original_language: "en",
    original_title: "X",
    overview:
      "In 1979, a group of young filmmakers set out to make an adult film in rural Texas, but when their reclusive, elderly hosts catch them in the act, the cast find themselves fighting for their lives.",
    popularity: 2295.421,
    poster_path: "/woTQx9Q4b8aO13jR9dsj8C9JESy.jpg",
    release_date: "2022-03-17",
    title: "X",
    video: false,
    vote_average: 6.8,
    vote_count: 762,
  },
  {
    adult: false,
    backdrop_path: "/nW5fUbldp1DYf2uQ3zJTUdachOu.jpg",
    genre_ids: [16, 878, 12, 28, 10751],
    id: 718789,
    original_language: "en",
    original_title: "Lightyear",
    overview:
      "Legendary Space Ranger Buzz Lightyear embarks on an intergalactic adventure alongside a group of ambitious recruits and his robot companion Sox.",
    popularity: 2170.425,
    poster_path: "/ox4goZd956BxqJH6iLwhWPL9ct4.jpg",
    release_date: "2022-06-15",
    title: "Lightyear",
    video: false,
    vote_average: 7.3,
    vote_count: 1773,
  },
  {
    adult: false,
    backdrop_path: "/wcKFYIiVDvRURrzglV9kGu7fpfY.jpg",
    genre_ids: [14, 28, 12],
    id: 453395,
    original_language: "en",
    original_title: "Doctor Strange in the Multiverse of Madness",
    overview:
      "Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.",
    popularity: 2155.823,
    poster_path: "/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg",
    release_date: "2022-05-04",
    title: "Doctor Strange in the Multiverse of Madness",
    video: false,
    vote_average: 7.5,
    vote_count: 5384,
  },
  {
    adult: false,
    backdrop_path: "/cu2xVhRZJrEkOHC8GQUWEJz3lk5.jpg",
    genre_ids: [16, 27, 35],
    id: 667276,
    original_language: "es",
    original_title: "Las Leyendas: El Origen",
    overview:
      "When a human baby crosses the Eternal Mirror, the portal between the living and the death opens its path to the beings from the underworld.",
    popularity: 1988.105,
    poster_path: "/7aju8OJ2F7jHkKJ68jfM6DGzMMD.jpg",
    release_date: "2021-02-15",
    title: "Legend Quest: The Origin",
    video: false,
    vote_average: 8.5,
    vote_count: 120,
  },
  {
    adult: false,
    backdrop_path: "/m7ldf8UdWSDztU8STGp8artmGoa.jpg",
    genre_ids: [18, 28, 12],
    id: 978436,
    original_language: "tr",
    original_title: "Adanis: Kutsal Kavga",
    overview: "",
    popularity: 1850.162,
    poster_path: "/1G5mt3uGUW5OWUcxcBUtHm5Zdd9.jpg",
    release_date: "2022-03-11",
    title: "Adanis: Kutsal Kavga",
    video: false,
    vote_average: 6.7,
    vote_count: 7,
  },
  {
    adult: false,
    backdrop_path: "/qViFGWCHaSmW4gP00RGh3xjMjsP.jpg",
    genre_ids: [27, 9648],
    id: 758724,
    original_language: "en",
    original_title: "The Cellar",
    overview:
      "When Keira Woods' daughter mysteriously vanishes in the cellar of their new house in the country, she soon discovers there is an ancient and powerful entity controlling their home that she will have to face or risk losing her family's souls forever.",
    popularity: 1752.549,
    poster_path: "/rtfGeS5WMXA6PtikIYUmYTSbVdg.jpg",
    release_date: "2022-03-25",
    title: "The Cellar",
    video: false,
    vote_average: 6.7,
    vote_count: 156,
  },
  {
    adult: false,
    backdrop_path: "/l99dylTOAMkwKSr54X5ytiEtnLA.jpg",
    genre_ids: [14, 12, 28],
    id: 919355,
    original_language: "en",
    original_title: "Dragon Knight",
    overview:
      "Many years after the war has been lost, and all the dragons slain, a lone knight travels the lands of Agonos seeking to raise an army against the demon lord Abaddon. When a healer's vision reveals that one dragon still lives, and together with an eager young squire, the knight sets off in search of the fabled creature. As the armies of Abaddon descend on the human kingdoms, the dragon is their last hope of fending off the horde, before it lays waste to the lands of men. But does the creature even exist? And if it does, will it fight for them once more?",
    popularity: 1688.928,
    poster_path: "/zkGFADykBtfPfTv7YJooxTH52ph.jpg",
    release_date: "2022-03-21",
    title: "Dragon Knight",
    video: false,
    vote_average: 7.1,
    vote_count: 23,
  },
  {
    adult: false,
    backdrop_path: "/t9K8ycUBCplWiICDOKRNRYcEH9e.jpg",
    genre_ids: [16, 28, 14],
    id: 810693,
    original_language: "ja",
    original_title: "劇場版 呪術廻戦 0",
    overview:
      "Yuta Okkotsu is a nervous high school student who is suffering from a serious problem—his childhood friend Rika has turned into a curse and won't leave him alone. Since Rika is no ordinary curse, his plight is noticed by Satoru Gojo, a teacher at Jujutsu High, a school where fledgling exorcists learn how to combat curses. Gojo convinces Yuta to enroll, but can he learn enough in time to confront the curse that haunts him?",
    popularity: 1662.205,
    poster_path: "/3pTwMUEavTzVOh6yLN0aEwR7uSy.jpg",
    release_date: "2021-12-24",
    title: "Jujutsu Kaisen 0",
    video: false,
    vote_average: 7.8,
    vote_count: 256,
  },
  {
    adult: false,
    backdrop_path: "/ocUp7DJBIc8VJgLEw1prcyK1dYv.jpg",
    genre_ids: [28, 12, 878],
    id: 634649,
    original_language: "en",
    original_title: "Spider-Man: No Way Home",
    overview:
      "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    popularity: 1658.434,
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    release_date: "2021-12-15",
    title: "Spider-Man: No Way Home",
    video: false,
    vote_average: 8,
    vote_count: 14756,
  },
  {
    adult: false,
    backdrop_path: "/27Mj3rFYP3xqFy7lnz17vEd8Ms.jpg",
    genre_ids: [28, 53],
    id: 725201,
    original_language: "en",
    original_title: "The Gray Man",
    overview:
      "When a shadowy CIA agent uncovers damning agency secrets, he's hunted across the globe by a sociopathic rogue operative who's put a bounty on his head.",
    popularity: 1654.623,
    poster_path: "/8cXbitsS6dWQ5gfMTZdorpAAzEH.jpg",
    release_date: "2022-07-13",
    title: "The Gray Man",
    video: false,
    vote_average: 7.1,
    vote_count: 1713,
  },
  {
    adult: false,
    backdrop_path: "/8wwXPG22aNMpPGuXnfm3galoxbI.jpg",
    genre_ids: [28, 12, 10751, 35],
    id: 675353,
    original_language: "en",
    original_title: "Sonic the Hedgehog 2",
    overview:
      "After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.",
    popularity: 1604.163,
    poster_path: "/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg",
    release_date: "2022-03-30",
    title: "Sonic the Hedgehog 2",
    video: false,
    vote_average: 7.7,
    vote_count: 2828,
  },
];
